# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # VMs are 2CPUs X 2GB
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end

  # All VMs are set up to be individual k3s kubernetes clusters
  config.vm.provision "shell" do |s|
    s.privileged = false
    s.path = "./bootstrap_k3s.sh"
  end

  # All VMs are set up to be bionic 64 boxes
  config.vm.box = "hashicorp/bionic64"

  # Give the VM a unique name
  config.vm.define "bijou" do |bijou|
    bijou.vm.hostname = "bijou"

    # set up consul for primary datacenter
    bijou.vm.provision "file", source: "./consul_primary.yaml", destination: "/tmp/consul_primary.yaml"
    bijou.vm.provision "shell" do |b|
      b.privileged = false
      b.path = "./bootstrap_consul_primary.sh"
    end
  end

  config.vm.define "sully" do |sully|
    sully.vm.hostname = "sully"
  end
end
