# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end

  config.vm.define "test" do |test|
    test.vm.box = "hashicorp/bionic64"
    test.vm.hostname = "test"
  end

end
